<?php
include_once("Config/database.php");
include_once("functions/comment_functions.php");
include_once("functions/general_functions.php");
include_once("functions/image_functions.php");
include_once("functions/like_functions.php");
include_once("functions/user_functions.php");
include_once("functions/security_key.php");
include_once("functions/Print_basic.php");
?>